### PR TITLE
fix ember-scheduler to work with native class syntax

### PR DESCRIPTION
**Pull request by toovy**
Using https://github.com/pzuraq/ember-native-class-polyfill and probably ember 3.6 there is an issue with the native class syntax and computed properties. A similar issue occurred in ember-concurrency (see https://github.com/machty/ember-concurrency/issues/261) and will be fixed in https://github.com/machty/ember-concurrency/pull/262.

I've changed the ember-scheduler to now work with the class based syntax for  the TaskProperty. As the test are still running I assume that the fix works.

### CODE REVIEW

**Comment by bistin** [comment]
It seems missing
```js
if (super.setup) {
     super.setup(...arguments);
}
```
in the setup function like https://github.com/machty/ember-concurrency/blob/master/addon/-task-property.js#L439-L442

After adding these code to setup function, it works in my project running in ember 3.6

**Comment by toovy** [comment]
I've added the conditional super call and updated this pull request. The CI still fails because of a dependency. I'll check that.

**Comment by toovy** [comment]
While ember-animated runs agains 3.6 in my simple test scenario the checks for ember try:one with ember-release ember-beta and ember-canary fail. I think that most of the issues are not related to ember-animated, e.g. willTransition is not used anywhere, maybe some test dependencies need to be updated. Any help is appreciated.

**Comment by cibernox** [comment]
@toovy This PR I just did on ember-app-scheduler should fix your problems: https://github.com/ember-app-scheduler/ember-app-scheduler/pull/192

**Comment by cibernox** [comment]
@toovy I believe that if you now delete yarn.lock and reinstall dependencies it should work.

**Comment by toovy** [comment]
@cibernox yes, removing the yarn.lock and reinstalling worked, thanks. So I guess we have to wait will the PR you made is merged. There is still the issue with `Uncaught TypeError: Ember.Test.adapter.exception is not a function` that seems to be outside ember-animated and also a `perform` issue that points to ember-concurrency.

**Comment by cibernox** [comment]
@toovy I turned out my PR wasn't needed, someone did it already. I closed it. Whatever is failing now is unrelated.

**Comment by ef4** [comment]
Thanks for helping with this.

**Comment by toovy** [comment]
np 👍
